apiVersion: v1
kind: Service
metadata:
  name: app-alpha-conformance
spec:
  type: ClusterIP
  selector:
    app: app-alpha-conformance
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
